/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exemplojradiobuttoncomboboxjbutton;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Admin
 */
public class ExemploRadioButton extends javax.swing.JFrame {
    Integer estilo = Font.PLAIN;
    Integer tamfonte;
    /**
     * Creates new form ExemploRadioButton
     */
    public ExemploRadioButton() {
        initComponents();
        grupo.add(selecao);
        grupo.add(selecao1);
        grupo.add(selecao2);
        grupo.add(selecao3);
        grupo.add(selecao4);
        
        grupo2.add(tam12);
        grupo2.add(tam14);
        grupo2.add(tam16);
        grupo2.add(tam18);
        
        exibir.setToolTipText("exibe o nome da cidade selecionada");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        grupo2 = new javax.swing.ButtonGroup();
        selecao1 = new javax.swing.JRadioButton();
        selecao2 = new javax.swing.JRadioButton();
        selecao3 = new javax.swing.JRadioButton();
        selecao4 = new javax.swing.JRadioButton();
        selecao = new javax.swing.JRadioButton();
        exibir = new javax.swing.JButton();
        vazio = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        titulo2 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        tam14 = new javax.swing.JRadioButton();
        tam12 = new javax.swing.JRadioButton();
        tam16 = new javax.swing.JRadioButton();
        tam18 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selecao1.setText("São Paulo");
        selecao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecao1ActionPerformed(evt);
            }
        });

        selecao2.setText("Minas Gerais");

        selecao3.setText("Amazonas");

        selecao4.setText("Rio Grande do Sul");

        selecao.setText("Rio de Janeiro");

        exibir.setText("exibir");
        exibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirActionPerformed(evt);
            }
        });

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nehum", "vermelho", "azul", "amarelo", "verde", "preto" }));

        titulo2.setText("Cidade");

        titulo.setText("Estilo");

        tam14.setText("tamanho: 14");
        tam14.setActionCommand("tamanho: 14");
        tam14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tam14ActionPerformed(evt);
            }
        });

        tam12.setText("tamanho: 12");
        tam12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tam12ActionPerformed(evt);
            }
        });

        tam16.setText("tamanho: 16");
        tam16.setActionCommand("tamanho: 16");
        tam16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tam16ActionPerformed(evt);
            }
        });

        tam18.setText("tamanho: 18");
        tam18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tam18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exibir)
                    .addComponent(selecao4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo2)
                            .addComponent(selecao3)
                            .addComponent(selecao2)
                            .addComponent(selecao1)
                            .addComponent(selecao))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(titulo)
                                        .addGap(33, 33, 33))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tam12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tam14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tam16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tam18)))))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vazio)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecao1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecao2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecao3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tam14)
                            .addComponent(tam12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tam16)
                            .addComponent(tam18))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selecao4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exibir)
                .addGap(41, 41, 41)
                .addComponent(vazio)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecao1ActionPerformed

    private void exibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirActionPerformed
    if(tam12.isSelected() == true){
        tamfonte = 12;
    }else if(tam14.isSelected() == true){
        tamfonte = 14;
    }else if(tam16.isSelected() == true){
        tamfonte = 16;
    }else if(tam18.isSelected() == true) {
        tamfonte = 18;
    }else{
        tamfonte = 12;
    }
    
    String cor = combo.getSelectedItem().toString();
    /*nehum
    vermelho
    azul
    amarelo
    verde
    preto*/
    if("vermelho".equals(cor)){
        vazio.setForeground(Color.RED);
    }
    
        
    vazio.setFont(new Font("", estilo, tamfonte));
    
    if(selecao.isSelected() == true){
        vazio.setText("A cidade escolhida foi: " + selecao.getText());
    }
    
    if(selecao1.isSelected() == true){
    vazio.setText("A cidade escolhida foi: " + selecao1.getText());
    }
    
    if(selecao2.isSelected() == true){
    vazio.setText("A cidade escolhida foi: " + selecao2.getText());
    }
    
    if(selecao3.isSelected() == true){
    vazio.setText("A cidade escolhida foi: " + selecao3.getText());
    }
    
    if(selecao4.isSelected() == true){
    vazio.setText("A cidade escolhida foi: " + selecao4.getText());
    }
    }//GEN-LAST:event_exibirActionPerformed

    private void tam14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tam14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tam14ActionPerformed

    private void tam12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tam12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tam12ActionPerformed

    private void tam16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tam16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tam16ActionPerformed

    private void tam18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tam18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tam18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExemploRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExemploRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExemploRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExemploRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExemploRadioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton exibir;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.ButtonGroup grupo2;
    private javax.swing.JRadioButton selecao;
    private javax.swing.JRadioButton selecao1;
    private javax.swing.JRadioButton selecao2;
    private javax.swing.JRadioButton selecao3;
    private javax.swing.JRadioButton selecao4;
    private javax.swing.JRadioButton tam12;
    private javax.swing.JRadioButton tam14;
    private javax.swing.JRadioButton tam16;
    private javax.swing.JRadioButton tam18;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel vazio;
    // End of variables declaration//GEN-END:variables
}
